language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover -s src/Test

env:
  - PYTHONPATH="${PYTHONPATH}:/src/Calculator:/src/CsvReader:/src/Fileutilities:/src/Statistics:/src/Test"

branches:
  only:
    - master