language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt

env:
  - PYTHONPATH="${PYTHONPATH}:Calculator:FileUtilities:Statistics:CsvReader:Test"
script:
  - python -m unittest discover -s Test


branches:
  only:
    - master